export const FETCH_CATEGORIES_STARTS = 'FETCH_CATEGORIES_STARTS';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS ';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED ';

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS ';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED ';


export const FETCH_PRODUCTS_STARTS = 'FETCH_PRODUCTS_STARTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS ';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED ';

export const AUTH_START = 'AUTH_START'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGOUT = 'LOGOUT'


